# Generated by Django 3.2.6 on 2021-08-15 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_datecomplited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='datecomplited',
            new_name='datecompleted',
        ),
    ]
